spring:
  application:
    name: shppngcart

  cloud:
    config:
      uri: http://localhost:8888
  redis:
    host: localhost
    port: 6379

  data:
    redis:
      repositories:
        enabled: true
