spring:
  application:
    name: shppngcart

  redis:
    host: localhost
    port: 6379

  data:
    redis:
      repositories:
        enabled: true

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    eureka-server-port: 9000
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
